# CBBEtoUBE - CBBE/3BA to UBE armor converter
# Copyright (C) 2026 DayOnly
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Build CBBEtoUBE.exe from CBBEtoUBE.spec via PyInstaller.
#
# Usage:
#   .\scripts\build_exe.ps1            # build (installs PyInstaller if missing)
#   .\scripts\build_exe.ps1 -Clean     # also wipe build\ and dist\ first
#
# Output: dist\CBBEtoUBE\CBBEtoUBE.exe  (a self-contained onedir bundle that
# embeds Python + numpy/scipy + the pynifly NiflyDLL.dll).

[CmdletBinding()]
param(
    [switch]$Clean
)

$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $PSScriptRoot
Set-Location $projectRoot
Write-Host "project root: $projectRoot"

$spec = Join-Path $projectRoot "CBBEtoUBE.spec"
if (-not (Test-Path $spec)) { throw "spec not found: $spec" }

# 1. Pick a Python and make sure PyInstaller is available in it.
$py = (Get-Command python -ErrorAction SilentlyContinue)
if (-not $py) { throw "python not found on PATH." }
Write-Host "python: $($py.Source)"

& python -c "import PyInstaller" 2>$null
if (-not $?) {
    Write-Host "PyInstaller not installed; installing into this interpreter..."
    & python -m pip install --upgrade pyinstaller
    if (-not $?) { throw "pip install pyinstaller failed." }
}
$piVer = (& python -c "import PyInstaller; print(PyInstaller.__version__)")
Write-Host "PyInstaller: $piVer"

# 1b. Build stamp. The exe has to be able to say WHICH build it is: the
# release string alone has shipped on a dozen different builds. Written as a
# gitignored module the bundle imports (src/build_info.py reads it; a source
# checkout without it reads as "source").
$gitSha = (& git rev-parse --short HEAD 2>$null); if (-not $gitSha) { $gitSha = "nogit" }
$dirtyFiles = (& git status --porcelain -- src CBBEtoUBE.spec cbbe_to_ube_main.py 2>$null) |
    Where-Object { $_ -and ($_ -notmatch '_build_stamp\.py') }
$dirty = if ($dirtyFiles) { "True" } else { "False" }
$utc = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$stampFile = Join-Path $projectRoot "src\_build_stamp.py"
@(
    "# GENERATED by scripts/build_exe.ps1 -- gitignored, do not edit.",
    "BUILD = {",
    "    'git': '$gitSha',",
    "    'dirty': $dirty,",
    "    'built_utc': '$utc',",
    "    'pyinstaller': '$piVer',",
    "}"
) -join "`n" | Set-Content -Path $stampFile -Encoding ascii -NoNewline
Write-Host "build stamp: $gitSha dirty=$dirty $utc"

# Reproducible build: the spec pins the RUNTIME hash seed; this pins the
# BUILD's, so two builds of the same tree produce the same .pyc bytes.
$env:PYTHONHASHSEED = "1"

# 2. Optional clean.
if ($Clean) {
    foreach ($d in @("build", "dist")) {
        $p = Join-Path $projectRoot $d
        if (Test-Path $p) { Write-Host "removing $p"; Remove-Item -Recurse -Force $p }
    }
}

# 3. Build.
Write-Host ""
Write-Host "building (this can take a few minutes the first time)..."
& python -m PyInstaller --noconfirm --clean $spec
if (-not $?) { throw "PyInstaller build failed." }

# 4. Report.
$exe = Join-Path $projectRoot "dist\CBBEtoUBE\CBBEtoUBE.exe"
if (-not (Test-Path $exe)) { throw "build finished but exe missing: $exe" }
Write-Host ""
Write-Host "BUILD OK"
Write-Host "  exe   : $exe"
Write-Host "  folder: $(Split-Path -Parent $exe)"
Write-Host ""
# Send an EXISTING install to deploy_exe.ps1, not the installer. The installer
# is for FIRST registration; naming it here pointed sessions at a script that
# used to wipe the live tools directory -- settings file, its backups and the
# run log with it -- and that still rewrites the MO2 INI, which a redeploy has
# no business touching.
Write-Host "Next:"
Write-Host "  already registered?  .\scripts\deploy_exe.ps1 -Dest <the path in"
Write-Host "                       ModOrganizer.ini's customExecutables binary=>"
Write-Host "                       robocopy /E, so your settings and logs survive"
Write-Host "  first time?          .\scripts\install_mo2_entry.ps1 -Mo2Root <modlist>"
