# CBBEtoUBE - CBBE/3BA to UBE armor converter
# Copyright (C) 2026 DayOnly
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""GENERATE docs/WARNINGS.md: every warning the converter can print, with what
it means and what to do, read out of the `warn(...)` calls in src/. #user-warnings

    python scripts/warning_surface.py            # write docs/WARNINGS.md
    python scripts/warning_surface.py --check    # exit 1 if the file is out of date

WHY GENERATED. The wording lives at 69 call sites in two modules; a hand-kept
list would drift the first time one changed. tests/test_user_warnings.py pins
the file to the calls, the way docs/TOOL_MAP.md is pinned to the tools, so a
new or reworded warning shows up in a diff of this document.

A `warn` call with fewer than 40 sites found is "measured NOTHING" and exits 2:
0/0 is not a pass. Every problem-level call must carry a consequence or a fix,
or the generator refuses -- a warning the reader cannot act on is the class
this exists to remove.

DEVELOPMENT TOOL -- not part of the shipped converter.
"""
from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO))

OUT = _REPO / "docs" / "WARNINGS.md"
MODULES = ("src/auto_convert.py", "src/nif_convert_writer.py")
FLOOR = 40
FIELDS = ("what", "where", "consequence", "fix", "level", "indent")


def _static(node) -> str:
    """The words of a string argument, with each runtime value shown as `…`."""
    if node is None:
        return ""
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.JoinedStr):
        out = []
        for v in node.values:
            out.append(v.value if isinstance(v, ast.Constant) else "…")
        return "".join(out)
    if isinstance(node, ast.Name):
        return "…"
    if isinstance(node, ast.Attribute):
        return "…"
    return "…"


def scan(repo: Path = _REPO) -> list[dict]:
    """Every `warn(...)` call in MODULES, in source order."""
    rows = []
    for rel in MODULES:
        path = repo / rel
        src = path.read_text(encoding="utf-8")
        tree = ast.parse(src)
        for node in ast.walk(tree):
            if not (isinstance(node, ast.Call) and isinstance(node.func, ast.Name)
                    and node.func.id == "warn"):
                continue
            row = {"module": rel, "line": node.lineno, "what": "", "where": "",
                   "consequence": "", "fix": "", "level": "!!"}
            if node.args:
                row["what"] = _static(node.args[0])
            for kw in node.keywords:
                if kw.arg in ("what", "where", "consequence", "fix"):
                    row[kw.arg] = _static(kw.value)
                elif kw.arg == "level":
                    v = kw.value
                    if isinstance(v, ast.Constant):
                        row["level"] = str(v.value)
                    elif isinstance(v, ast.Name):
                        row["level"] = {"PROBLEM": "!!", "NOTE": "NOTE:"}.get(v.id, v.id)
            rows.append(row)
    rows.sort(key=lambda r: (MODULES.index(r["module"]), r["line"]))
    return rows


def unactionable(rows: list[dict]) -> list[dict]:
    """Problem-level warnings that say neither what they mean nor what to do."""
    return [r for r in rows if r["level"] == "!!" and not (r["consequence"] or r["fix"])]


def render(rows: list[dict]) -> str:
    n_problem = sum(1 for r in rows if r["level"] == "!!")
    n_note = len(rows) - n_problem
    out = [
        "# Every warning the converter can print",
        "",
        "Generated by `python scripts/warning_surface.py` from the `warn(...)` calls in",
        "the batch runner and the mesh writer; `tests/test_user_warnings.py` keeps it",
        "current. A `!!` line is a problem; a `NOTE:` line is information. Each entry",
        "gives the line as it appears in the run log (`…` stands for the value printed",
        "at run time), what it means for the run, and what to do next.",
        "",
        f"**{n_problem}** problem warnings and **{n_note}** notes.",
        "",
    ]
    for module in MODULES:
        mine = [r for r in rows if r["module"] == module]
        if not mine:
            continue
        out.append(f"## {module}")
        out.append("")
        for r in mine:
            head = r["what"].strip()
            if r["where"]:
                head += f" -- {r['where'].strip()}"
            out.append(f"- `{r['level']} {head}`")
            if r["consequence"]:
                out.append(f"  - means: {r['consequence'].strip()}")
            if r["fix"]:
                out.append(f"  - fix: {r['fix'].strip()}")
        out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if docs/WARNINGS.md is out of date")
    a = ap.parse_args()
    rows = scan()
    if len(rows) < FLOOR:
        print(f"measured NOTHING -- {len(rows)} warn() call(s) found (floor {FLOOR}); "
              "0/0 is not a pass")
        return 2
    bad = unactionable(rows)
    if bad:
        for r in bad:
            print(f"UNACTIONABLE {r['module']}:{r['line']}: {r['what'].strip()!r} has "
                  "neither a consequence nor a fix")
        return 2
    want = render(rows)
    if a.check:
        have = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if have != want:
            print("docs/WARNINGS.md is out of date; run python scripts/warning_surface.py")
            return 1
        print(f"docs/WARNINGS.md is current ({len(rows)} warnings)")
        return 0
    OUT.write_bytes(want.encode("utf-8"))
    print(f"wrote docs/WARNINGS.md ({len(rows)} warnings)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
